---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ledger-api-secrets
  namespace: payments
spec:
  encryptedData:
    DB_PASSWORD: AgA6iF2WgMezOE+FZPVH+P9/iuEgeeUtO+yyM5JJ53RH/9x3C10CU1AdkN0DYizR5tpWxGIO0GKZ0mGaHcyQWZQc1WCU5ThValO9rPcTl2/cysI0nxsHN5qYOs1GZagoY8WeVZGq0EYywjeMYfqqkULXfTx9puFM36w0iyCiREuFhrjUf8JTlK0S3WK9VuPGWmdttG/HkgFhqVARqmGKuY3ZEV8eXi2BuX769BKgdB6Pbb/JHXBZcI3PM4BtA8xj4BlOFvb/LHVG6pNQ1oxug1juMlV2i0uPDzPj5b2CXjdpSk58A3qJv5Jo9zDze7XKc8XRJV/OSvb5hrHRBrrg9CXOo+ynEuUoq0Y95ADjJbVahW1z5zDcEZB5YgQTkYiGzcqyM0e6fM8sU3p2fc0XXeqqTMDiVZt6Gvss8FdQOkewjjdc3axC1Boxd7Jf/DYYLr9JYj/hzBBXlWcs0ZHhOhYqXfkW9WGRPvHVExt0bGJiPK2t+Gefd/TXrnOaV173uSIX7JPOlZYQUI1464gPXJKBmoCrsl67P9UQoeKzkeaYRBGw1cjr9Te5WaK0KwSgiTpTFZz+8w7wD/o599D6Kah5bCXi5OUf649KIuY6mdBT83cFaye/db8iPZFc9TwboGEND+RJS9wLjiCS0jlFAwvwQ7NPMTyEqmt4MkfKCCJOKcupS5mK91//G6wRX6to5HQ703EieQUTYxq/jxv0v1/W
    STRIPE_API_KEY: AgC0fcqngWQ1lvplreNRzUy8rtrMm4Zg++fWDZQvw2qKcpVxgzv6TWw1Y8sxpUZ9PcDxJTmGhF9ga6oJ4GOxJkHANM1+9oA/eaI/qPQ4bRNFK8zZ4PEMyg/k1dNeHaOHmI/XiL3cF/MOZOyDfyoB7kQKwapZI+JnNY99425f+o2nxsmOscacWQskbU85+u9Ym0zPj3clPGnnXf+rmG9V6RKXd+f8sXRbgr6QT0yk3UCxXi7P4hP9JIPCTP3WdG/RoCFnuX/rk/6KCPcLspgnO5g/eTYCATpQv08mOBBMIyEs5Cne6o3U8Vye2cLY23jMILsJYB1uFW1KJEVQcenYw0ks5iXEgzAiVd2WMzDg95ADDO3g5xVoB3IEvdfhIKsfWBkLi1LhZaWVT/Mu4zBugfORhSje0lQlRdABaQh1RpHTnAk92VZ0zlDBRj9K0LfPf6mUe55XdGDpLIWdG2znKlzEo2b9acJt23A95T/Nngb/591+BkR+uJ7uGq9PmPMqSUtAvnLAlIs9RxkvnmPLESw0o4O6R9bp4sCuUnxfh2wAqAplclL36EVA0cmJ24rv3pJ1U2pTd0T2Wts1PM9E+WO3Ho3ipTni8gvrTPWTY8LgO2QeY81m7LiRIUQjXwYEi8wOPB3lgFtxYzE5fDIN9SMT/pVJ2WwMJYoT83DgaA6k1wLROO5jZk+uXqTAM0P7QbHAf3jw0jFB+wjC1zKTZBw=
  template:
    metadata:
      name: ledger-api-secrets
      namespace: payments
